export const hiraganas = {
  vowels: [
    { character: "あ", translation: "A" },
    { character: "い", translation: "I" },
    { character: "う", translation: "U" },
    { character: "え", translation: "E" },
    { character: "お", translation: "O" },
  ],
  k: [
    { character: "か", translation: "KA" },
    { character: "か", translation: "KI" },
    { character: "か", translation: "KU" },
    { character: "か", translation: "KE" },
    { character: "か", translation: "KO" },
  ],
  s: [
    { character: "さ", translation: "SA" },
    { character: "し", translation: "SHI" },
    { character: "す", translation: "SU" },
    { character: "せ", translation: "SE" },
    { character: "そ", translation: "SO" },
  ],
  t: [
    { character: "た", translation: "TA" },
    { character: "ち", translation: "CHI" },
    { character: "つ", translation: "TSU" },
    { character: "て", translation: "TE" },
    { character: "と", translation: "TO" },
  ],
  n: [
    { character: "な", translation: "NA" },
    { character: "に", translation: "NI" },
    { character: "ぬ", translation: "NU" },
    { character: "ね", translation: "NE" },
    { character: "の", translation: "NO" },
  ],
  h: [
    { character: "は", translation: "HA" },
    { character: "ひ", translation: "HI" },
    { character: "ふ", translation: "HU" },
    { character: "へ", translation: "HE" },
    { character: "ほ", translation: "HO" },
  ],
  m: [
    { character: "ま", translation: "MA" },
    { character: "み", translation: "MI" },
    { character: "む", translation: "MU" },
    { character: "め", translation: "ME" },
    { character: "も", translation: "MO" },
  ],
  r: [
    { character: "ら", translation: "RA" },
    { character: "り", translation: "RI" },
    { character: "る", translation: "RU" },
    { character: "れ", translation: "RE" },
    { character: "ろ", translation: "RO" },
  ],
  y_w: [
    { character: "や", translation: "YA" },
    { character: "ゆ", translation: "YU" },
    { character: "よ", translation: "YO" },
    { character: "わ", translation: "WA" },
    { character: "を", translation: "WO" },
  ],
  en: [{ character: "ん", translation: "N" }],
};

export const katakanas = {
  vowels: [
    { character: "ア", translation: "A" },
    { character: "イ", translation: "I" },
    { character: "ウ", translation: "U" },
    { character: "エ", translation: "E" },
    { character: "オ", translation: "O" },
  ],
  k: [
    { character: "カ", translation: "KA" },
    { character: "キ", translation: "KI" },
    { character: "ク", translation: "KU" },
    { character: "ケ", translation: "KE" },
    { character: "コ", translation: "KO" },
  ],
  s: [
    { character: "サ", translation: "SA" },
    { character: "シ", translation: "SHI" },
    { character: "ス", translation: "SU" },
    { character: "セ", translation: "SE" },
    { character: "ソ", translation: "SO" },
  ],
  t: [
    { character: "タ", translation: "TA" },
    { character: "チ", translation: "CHI" },
    { character: "ツ", translation: "TSU" },
    { character: "テ", translation: "TE" },
    { character: "ト", translation: "TO" },
  ],
  n: [
    { character: "ナ", translation: "NA" },
    { character: "ニ", translation: "NI" },
    { character: "ヌ", translation: "NU" },
    { character: "ネ", translation: "NE" },
    { character: "ノ", translation: "NO" },
  ],
  h: [
    { character: "ハ", translation: "HA" },
    { character: "ヒ", translation: "HI" },
    { character: "フ", translation: "HU" },
    { character: "ヘ", translation: "HE" },
    { character: "ホ", translation: "HO" },
  ],
  m: [
    { character: "ホ", translation: "MA" },
    { character: "ミ", translation: "MI" },
    { character: "ム", translation: "MU" },
    { character: "メ", translation: "ME" },
    { character: "モ", translation: "MO" },
  ],
  r: [
    { character: "ラ", translation: "RA" },
    { character: "リ", translation: "RI" },
    { character: "ル", translation: "RU" },
    { character: "レ", translation: "RE" },
    { character: "ロ", translation: "RO" },
  ],
  y_w: [
    { character: "ヤ", translation: "YA" },
    { character: "ユ", translation: "YU" },
    { character: "ヨ", translation: "YO" },
    { character: "ワ", translation: "WA" },
    { character: "ヲ", translation: "WO" },
  ],
  en: [{ character: "ン", translation: "N" }],
};
